name: main
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependencies...
        run: npm install
      - name: checking pwd
        run: pwd
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Building react app...
        run: npm run build 
      - name: checking wd
        run: pwd
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Deploying app...
        run: echo 'Deploy'
